name: CI

on: [ pull_request, push ]

jobs:
  test:
    name: test jdk${{ matrix.java }}
    strategy:
      matrix:
        java: [ 8, 11, 16 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          java-package: jdk
          cache: 'gradle'
      - name: Build
        run: ./gradlew build
