name: test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test ${{ matrix.os }} JDK${{ matrix.java }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 17, 23 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle build
        run: ./gradlew build

      - name: Upload Unit Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.os }}-JDK${{ matrix.java }}
          path: '**/build/reports/tests/'
